name: uniapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  injectable: ^2.5.0
  gap: ^3.0.1
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  path_provider: ^2.1.5
  timeago: ^3.7.0
  loader_overlay: ^5.0.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  material_symbols_icons: ^4.2815.0
  supabase_flutter: ^2.8.4
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  get_it: ^8.0.3
  form_builder_validators: ^11.1.2
  flutter_form_builder: ^10.0.1
  velocity_x: ^4.3.1
  sqflite: ^2.4.2
  like_button: ^2.0.5
  flutter_card_swiper: ^7.0.2
  readmore: ^3.0.0
  cached_network_image: ^3.4.1
  video_trimmer: ^5.0.0
  get_thumbnail_video: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15

dependency_overrides:
  intl: ^0.20.0

flutter:
  uses-material-design: true
